// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkxjvsezqrutchjopmwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreGp2c2V6cXJ1dGNoam9wbXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTg4NjYsImV4cCI6MjA1ODE5NDg2Nn0.cEYHVzRBUhUkM2N3epBJA4yg-NwCO5fDLHVwE8NfcOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);